{
    "data_path": "/home/pk222/projects/PDEControl_DPC/datasets/heat_smooth_f_dataset.npz",
    "samples_to_load": 100,
    "seed": 0,
    "train_frac": 0.8,
    "batch_size": 75,
    "num_steps": 200,
    "log_iter": 10,
    "lr": 1e-3,
    "transition_steps": 2000,
    "decay_rate": 0.9,
    "sample_id_rollout": 5,
    "save_iter": 5000,
    "save_best": 1,
    "save_last": 1,
    "resume_path": "",
    "resume_strict": 1,
    "device": "auto",
    "dtype": "float32",
    "num_samples_to_evaluate": 5,
}